name: first

on: push

jobs:
  job1:
    name: First job from ${{ github.actor }} is learning GitHub Actions
    runs-on: ubuntu-latest
    steps:
    - name: Step One
      uses: actions/checkout@v2
    - name: Step Two
      run: env | sort
    - name: Step Three Creating artifacts
      uses: actions/upload-artifact@v3
      with:
        name: abc
        path: ./

  job2:
    name: Second job from ${{ github.actor }}
    runs-on: windows-latest
    steps:
    - name: Step One
      uses: actions/checkout@v2
    - name: Step Two
      run: "Get-ChildItem Env: | Sort-Object Name"
